// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjsrxandwpznwmjacmeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qc3J4YW5kd3B6bndtamFjbWV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NDUzNjAsImV4cCI6MjA2MTAyMTM2MH0.0v5kLEiwafd2dPahuiIG9isdNFKfjhwqxf7RYHUPka0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);